# Sentiment Analysis of Twitter Opinions on Apple and Google Products: A Tool for Kenya's Parliamentary ICT Committee Decision Making

## Overview

In the age of digital communication, social media platforms like Twitter have become instrumental in gauging public opinion. These platforms, rife with real-time reactions, comments, and sentiments, offer a goldmine of data that can be harnessed for various purposes. From businesses seeking to understand consumer preferences to governmental bodies aiming to gauge public sentiment on policies, the applications are manifold. One such significant application is in the realm of legislative decision-making, where understanding public sentiment can lead to more informed and representative decisions.

Nyika Analytika, a reknown data analytics company, has embarked on a pioneering project to analyze Twitter sentiments regarding two of the world's leading tech giants: Apple and Google. These companies, with their vast array of products and services, have become household names, eliciting strong opinions from users worldwide. By understanding the sentiments around these brands, it becomes feasible to predict public reactions to any legislative or regulatory changes concerning them.

Kenya's Parliamentary ICT Committee, responsible for overseeing and formulating policies related to Information and Communication Technology (ICT), recognizes the importance of this endeavor. As the world becomes increasingly digital and interconnected, the actions of major tech companies can have wide-reaching implications. Whether it's about data privacy, product pricing, or any other tech-related issue, understanding public sentiment can guide the committee in its legislative and oversight functions.

This project seeks to harness the power of Natural Language Processing (NLP) to analyze and categorize Twitter sentiments. The ultimate goal is to provide the ICT Committee with actionable insights that reflect the public's views, aiding them in making decisions that are in line with the interests and concerns of the citizenry.

In the following sections, we will delve deeper into the methodology, the dataset sourced from data.world, the challenges faced, and the results of our analysis. Through this endeavor, we aim to bridge the gap between public sentiment and legislative action, ensuring a more harmonious and informed relationship between tech giants, their consumers, and regulatory bodies.

## Business Understanding

The arena of modern business is no longer restricted to boardrooms, production lines, or sales pitches. Instead, it thrives on the digital expanse, where real-time conversations, reviews, and sentiments shape the dynamics of brands and industries. At the heart of this digital conversation is social media, with platforms like Twitter becoming the epicenter of brand discussions, user feedback, and public opinion.

**The Power of Public Sentiment**

The sentiment of the masses, especially when expressed freely on platforms like Twitter, carries immense weight. Not only does it reflect the immediate public reaction to products, services, or policies, but it also serves as a predictor of future trends, behaviors, and market shifts. For businesses, understanding this sentiment is crucial for product development, marketing strategies, and reputation management. For governmental bodies, it offers a genuine reflection of the public's pulse on policies, decisions, and changes.

**Apple and Google: More Than Just Tech Giants**

Apple and Google, two of the world's most influential tech brands, are more than just businesses. They symbolize a lifestyle, an ethos, and to some extent, ideologies. Their products, ranging from smartphones and software to services like cloud storage and music streaming, touch the lives of billions globally. As such, sentiments around these brands are not merely reflections of product satisfaction; they encapsulate broader themes of privacy, technological advancement, affordability, and societal impact.

**The Kenyan Context**

Kenya, with its burgeoning tech scene and rapidly digitizing economy, represents a significant market for global tech giants. The nation's youth-driven population, increased mobile penetration, and a thriving startup ecosystem, especially in cities like Nairobi, make it a focal point for brands like Apple and Google. As these companies make inroads into the Kenyan market, understanding the local sentiment becomes paramount. Moreover, as Kenya positions itself as a tech hub in East Africa, the decisions made by its Parliamentary ICT Committee can influence not just local, but regional tech dynamics.

**Legislation and Oversight in the Age of Tech**

In a world increasingly driven by data, digital privacy, and technological innovations, the role of legislative bodies like Kenya's Parliamentary ICT Committee becomes even more pivotal. Their decisions can shape the trajectory of the nation's digital future, influencing everything from startup growth and foreign tech investments to digital rights and internet freedoms. In making these decisions, the committee must strike a balance between fostering innovation, ensuring consumer rights, and maintaining security. Herein lies the essence of our project: to provide the committee with a tool that offers insights into public sentiment, aiding in more balanced, representative, and informed decision-making.

**Sentiment Analysis: The Bridge Between Brands and Policy**

By harnessing the power of Natural Language Processing to analyze sentiments around Apple and Google, this project aims to bridge the gap between the public, brands, and policymakers. It's not just about positive or negative feedback on a product. It's about understanding deeper themes of trust, expectations, concerns, and aspirations that people associate with these brands. Such insights can inform not only business strategies for Apple and Google but also guide the ICT Committee in understanding potential public reactions to tech-related legislation and regulations.

Business understanding of this project extends beyond mere data analysis. It touches upon the intricate web of interactions between brands, consumers, technological innovations, and legislative frameworks. By delving into the sentiments of Twitter users, Nyika Analytika seeks to offer a comprehensive view of the public's stance on two of the world's most influential tech brands, thereby aiding Kenya's Parliamentary ICT Committee in its noble endeavor of shaping the nation's digital destiny.

## Statement of the Problem

In the digital age, where information flows seamlessly across borders and opinions are voiced in real-time, understanding public sentiment has become paramount for both businesses and governments. The sentiments, often scattered across platforms and buried within vast amounts of textual data, hold valuable insights that can guide decision-making processes. Among the platforms, Twitter stands out as a premier space for consumers, professionals, and enthusiasts to voice their opinions on products, brands, and policies.

Two of the most discussed entities in the tech world are Apple and Google. Their vast product portfolios, ranging from hardware like smartphones and laptops to software solutions and digital services, have garnered them billions of users worldwide. Given their global influence, any sentiment, whether positive or negative, concerning these brands can ripple into wider economic, technological, and even political implications.

**The Challenge:**

Kenya's Parliamentary ICT Committee, tasked with overseeing the nation's technological trajectory, faces a significant challenge. As they contemplate legislation and regulatory changes that may impact or be influenced by tech giants like Apple and Google, they require a comprehensive understanding of public sentiment. The following questions arise:

1. How does the Kenyan public perceive Apple and Google products and services?
2. Are there specific products or services from these tech giants that receive more positive or negative feedback than others?
3. How do public sentiments correlate with potential legislative or regulatory changes? 
4. Can sentiment analysis provide predictive insights into how the public might react to future tech-related policies?

**The Objective:**

Nyika Analytika aims to address these challenges by designing a robust sentiment analysis model, leveraging Natural Language Processing (NLP) techniques, to analyze tweets about Apple and Google. The objective is multi-faceted:

1. **Quantitative Analysis**: To categorize the vast number of tweets into distinct sentiment categories - positive, negative, or neutral.
2. **Qualitative Analysis**: To delve deeper into the sentiments to understand specific concerns, praises, or neutral observations associated with the brands or their products.
3. **Insight Generation**: To extrapolate findings and generate actionable insights that the ICT Committee can use to predict public reactions to potential legislative changes.
4. **Recommendation Framework**: Based on the sentiment analysis, recommend areas of focus for the committee, highlighting products or issues that require particular attention.

**Significance of the Problem:**

The importance of this problem cannot be understated. An accurate sentiment analysis tool:

1. Provides a pulse on the nation's sentiment towards influential tech brands, informing both the brands and the legislative bodies.
2. Acts as a proactive tool for the ICT Committee, allowing them to anticipate public reactions and adjust their strategies accordingly.
3. Bridges the gap between public sentiment and legislative action, ensuring that the policies formulated are in line with the aspirations, concerns, and needs of the citizenry.

The core problem Nyika Analytika seeks to address is the extraction, analysis, and interpretation of public sentiment on Twitter concerning Apple and Google. The results aim to equip Kenya's Parliamentary ICT Committee with a nuanced understanding of public opinion, enabling them to make informed and representative decisions in the realm of tech policy and regulation.

## Data Understanding

For any analytical endeavor, the initial and crucial step is understanding the data at hand. The richness, accuracy, and comprehensiveness of data can greatly influence the outcome of any analysis. Given that our focus is on analyzing sentiments towards Apple and Google based on tweets, it's essential to gain a deep understanding of the dataset we have.

**1. Source of the Data:**

The dataset provided is sourced from data.world, a renowned platform that curates and hosts diverse datasets. Contributors at data.world have meticulously evaluated tweets related to various brands and products, and for our project, we'll be concentrating on sentiments expressed about Apple and Google.

**2. Data Dimensions:**

Before diving into any analysis, it's important to understand the dimensions of the dataset:
- **Number of Entries**: Indicates the volume of data and potential sample size.
- **Attributes/Columns**: Provides insight into the kind of information available. For sentiment analysis, we'd expect attributes like the tweet content, sentiment label (positive, negative, neutral), timestamp, and possibly the brand or product being discussed.

**3. Data Quality:**

The reliability of any analysis is directly proportional to the quality of the data used. Key quality metrics to consider include:
- **Completeness**: Are there any missing values in crucial columns like tweet content or sentiment label?
- **Consistency**: Are the entries standardized, or are there inconsistencies in how data is presented?
- **Accuracy**: While hard to determine without a reference, any glaring inaccuracies or anomalies should be noted.

**4. Granularity of Sentiment Labels:**

Understanding the granularity of sentiment labels is vital. Basic sentiment analysis might categorize sentiments as positive, negative, or neutral. However, more nuanced datasets might provide more granular sentiments like 'very positive', 'somewhat negative', etc.

**5. Distribution of Sentiments:**

A preliminary understanding of how sentiments are distributed can offer valuable insights. For instance, is there an overwhelming majority of neutral tweets, or is there a balanced distribution of positive and negative sentiments?

**6. Temporal Data:**

If timestamps are available, understanding the temporal distribution of the data is essential. This can help in identifying trends over time or understanding the impact of specific events or product launches on public sentiment.

**7. Brand/Product Specific Information:**

Given that the focus is on Apple and Google, it's crucial to identify:
- Which products or services are most frequently discussed?
- Is the sentiment predominantly positive or negative for specific products?

**8. Potential Challenges:**

Every dataset presents its unique challenges. For sentiment analysis on tweets, common challenges include:
- **Sarcasm**: Tweets may contain sarcasm, which can be challenging for models to interpret correctly.
- **Language Variability**: Tweets might be in different languages, dialects, or contain colloquial terms.
- **Short Texts**: Due to Twitter's character limit, tweets might be concise, making it challenging to discern sentiment accurately.

To kickstart our detailed data understanding, let's take a preliminary look at the provided dataset. We'll examine its structure, the first few entries, and gather some basic statistics.

In [1]:
import pandas as pd

# Loading the dataset
try:
    data = pd.read_csv('judge-1377884607_tweet_product_company.csv', encoding="ISO-8859-1")
    data_head = data.head()
    data_shape = data.shape
except Exception as e:
    error_message = str(e)
    data_head, data_shape, error_message

data_head
data_shape

(9093, 3)

**Dataset Overview:**

1. **Dimensions:**
- The dataset comprises 9093 entries and 3 attributes.
2. **Attributes:**
- `tweet_text`: This contains the actual content of the tweet.
- `emotion_in_tweet_is_directed_at`: Indicates which brand or product the emotion in the tweet is directed towards.
- `is_there_an_emotion_directed_at_a_brand_or_product`: Categorizes the sentiment of the tweet as either positive, negative, neutral, or no sentiment.

Let's further analyze some key aspects of the data for a deeper understanding. We'll look into:

- Distribution of sentiments.
- Number of missing values in each column.
- A glimpse of the brands/products mentioned in the dataset.

In [2]:
# Distribution of sentiments
sentiment_distribution = data['is_there_an_emotion_directed_at_a_brand_or_product'].value_counts()

# Number of missing values in each column
missing_values = data.isnull().sum()

# Glimpse of the brands/products mentioned
brands_distribution = data['emotion_in_tweet_is_directed_at'].value_counts()

sentiment_distribution, missing_values, brands_distribution

(is_there_an_emotion_directed_at_a_brand_or_product
 No emotion toward brand or product    5389
 Positive emotion                      2978
 Negative emotion                       570
 I can't tell                           156
 Name: count, dtype: int64,
 tweet_text                                               1
 emotion_in_tweet_is_directed_at                       5802
 is_there_an_emotion_directed_at_a_brand_or_product       0
 dtype: int64,
 emotion_in_tweet_is_directed_at
 iPad                               946
 Apple                              661
 iPad or iPhone App                 470
 Google                             430
 iPhone                             297
 Other Google product or service    293
 Android App                         81
 Android                             78
 Other Apple product or service      35
 Name: count, dtype: int64)

Breaking down our findings from the initial exploration of the dataset:

**Sentiment Distribution**:
- **No emotion toward brand or product**: 5,389 tweets
- **Positive emotion**: 2,978 tweets
- **Negative emotion**: 570 tweets
- **I can't tell**: 156 tweets

This distribution suggests that a significant portion of the tweets does not express any specific emotion towards the brands or products. Additionally, there's a notable skew towards positive sentiments over negative ones.

**Missing Values**:
- **tweet_text**: 1 missing value
- **emotion_in_tweet_is_directed_at**: 5,802 missing values

It's worth noting that a large number of entries do not specify which brand or product the emotion in the tweet is directed towards. This could pose a challenge, especially since our focus is on Apple and Google products. The missing tweet text is negligible and can be handled during the data preprocessing phase.

**Brands/Products Distribution**:
- **iPad**: 946 mentions
- **Apple**: 661 mentions
- **iPad or iPhone App**: 470 mentions
- **Google**: 430 mentions
- **iPhone**: 297 mentions
- **Other Google product or service**: 293 mentions
- **Android App**: 81 mentions
- **Android**: 78 mentions
- **Other Apple product or service**: 35 mentions

From a cursory look, Apple-related products and services (like iPad, iPhone, and their apps) dominate the dataset in terms of mentions. Google and its associated products/services also have a significant presence.

### **Inference**:

The dataset offers a substantial volume of tweets to work with, and while there are missing values in the "brand/product" column, the "sentiment" column is fully populated, allowing for comprehensive sentiment analysis. The next steps would involve rigorous data cleaning and preprocessing to ensure the dataset is primed for sentiment analysis using NLP techniques.

## Data Exploration

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

# Setting up the aesthetics for the plots
sns.set_style("whitegrid")

# Initializing the figure
plt.figure(figsize=(20, 15))

# Creating subplots: 3 plots (Sentiment Distribution, Brands/Products Distribution, and Missing Values)
plt.subplots_adjust(hspace=0.5)

# 1. Sentiment Distribution
plt.subplot(3, 1, 1)
sentiment_distribution.plot(kind='bar', color='skyblue')
plt.title("Distribution of Sentiments", fontsize=16)
plt.xlabel("Sentiment Categories", fontsize=14)
plt.ylabel("Number of Tweets", fontsize=14)

# 2. Brands/Products Distribution
plt.subplot(3, 1, 2)
brands_distribution.plot(kind='bar', color='lightcoral')
plt.title("Distribution of Brands/Products Mentions", fontsize=16)
plt.xlabel("Brands/Products", fontsize=14)
plt.ylabel("Number of Mentions", fontsize=14)

# 3. Missing Values
plt.subplot(3, 1, 3)
missing_values.plot(kind='bar', color='lightgreen')
plt.title("Missing Values in the Dataset", fontsize=16)
plt.xlabel("Columns", fontsize=14)
plt.ylabel("Number of Missing Values", fontsize=14)

plt.tight_layout()
plt.show()

**Distribution of Sentiments**:
- The majority of tweets in the dataset do not express any specific emotion towards the brands or products. These are categorized under "No emotion toward brand or product".
- Positive sentiments are considerably more prevalent than negative ones, suggesting a generally favorable opinion towards the brands/products in the dataset.
- A smaller portion of tweets fall under the "I can't tell" category, indicating ambiguity in discerning the sentiment.

**Distribution of Brands/Products Mentions**:
- Apple products, specifically the iPad, dominate the dataset in terms of mentions. This is followed by Apple as a brand and the combined mentions of iPad or iPhone apps.
- Google, as a brand, has a significant number of mentions, rivalling Apple's individual products. 
- Other Google products or services, Android, and Android Apps also make appearances, but with fewer mentions. 
- Mentions categorized under "Other Apple product or service" are relatively low.

**Missing Values in the Dataset**:
- The column `emotion_in_tweet_is_directed_at`, which indicates the brand or product the tweet is about, has a substantial number of missing values. This could potentially pose challenges during analysis, as understanding the context or target of a tweet is crucial for sentiment analysis.
- The tweet text has a negligible missing value count.

This visual exploration provides a clearer picture of the dataset's contents and highlights areas that might require attention during data preprocessing, especially handling missing values. As we proceed, it'll be essential to address these gaps and ensure the data is well-suited for sentiment analysis.

### Data Preprocessing

In [4]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string

# Downloading the necessary NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# 1. Remove Duplicate Records
data = data.drop_duplicates()

# 2. Handle Missing Values
# Given the nature of our analysis, we'll drop rows with missing 'tweet_text' since they offer no value.
data = data.dropna(subset=['tweet_text'])

# For 'emotion_in_tweet_is_directed_at', we'll fill missing values with 'Unknown' as we don't have context to impute them.
data['emotion_in_tweet_is_directed_at'].fillna('Unknown', inplace=True)

# 3. Text Cleaning Function
def clean_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove special characters, punctuation, and unwanted symbols
    text = ''.join([char for char in text if char not in string.punctuation])
    # Tokenize
    tokens = word_tokenize(text)
    # Remove stopwords
    tokens = [word for word in tokens if word not in stopwords.words('english')]
    return ' '.join(tokens)

# Apply the cleaning function to the 'tweet_text' column
data['cleaned_tweet_text'] = data['tweet_text'].apply(clean_text)

# Check the first few entries of the cleaned data
data_cleaned_head = data.head()

data_cleaned_head

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\pkisi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pkisi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


tweet_text  \
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...   
1  @jessedee Know about @fludapp ? Awesome iPad/i...   
2  @swonderlin Can not wait for #iPad 2 also. The...   
3  @sxsw I hope this year's festival isn't as cra...   
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...   

  emotion_in_tweet_is_directed_at  \
0                          iPhone   
1              iPad or iPhone App   
2                            iPad   
3              iPad or iPhone App   
4                          Google   

  is_there_an_emotion_directed_at_a_brand_or_product  \
0                                   Negative emotion   
1                                   Positive emotion   
2                                   Positive emotion   
3                                   Negative emotion   
4                                   Positive emotion   

                                  cleaned_tweet_text  
0  wesley83 3g iphone 3 hrs tweeting riseaustin d...  
1  jessedee know fludapp awesome ipadiphone app y...  
2              swonderlin wait ipad 2 also sale sxsw  
3  sxsw hope years festival isnt crashy years iph...  
4  sxtxstate great stuff fri sxsw marissa mayer g...

Here's a breakdown of the preprocessing steps we've taken:

**Duplicate Records Removal**: Any duplicate rows were removed to avoid redundancy.

**Handling Missing Values**: We dropped rows with missing tweet text and filled in missing values in the `emotion_in_tweet_is_directed_at` column with the label 'Unknown'.

**Text Cleaning**: 
    - Converted the text to lowercase to ensure uniformity.
    - Removed special characters, punctuation, and other unwanted symbols.
    - Tokenized the text by splitting based on whitespace.
    - Removed common English stopwords, which generally don't carry much sentiment information.
    
The cleaned text is now stored in the `cleaned_tweet_text` column. 

The next step would involve further processing, like text normalization (stemming or lemmatization) and vectorization, before feeding it into a sentiment analysis model. However, for the current scope of data preprocessing, we've prepared the data for analysis.

## Sentiment Labeling

Here, we create a new column in the dataset to assign sentiment labels to each tweet. 

In [5]:
# Function to assign sentiment labels
def assign_sentiment_label(sentiment):
    if "Positive emotion" in sentiment:
        return "Positive"
    elif "Negative emotion" in sentiment:
        return "Negative"
    elif "No emotion" in sentiment:
        return "Neutral"
    else:
        return "Unknown"  # For sentiments labeled as "I can't tell"

# Create a new column 'sentiment_label' using the function
data['sentiment_label'] = data['is_there_an_emotion_directed_at_a_brand_or_product'].apply(assign_sentiment_label)

# Check the first few entries to see the new 'sentiment_label' column
data_labelled_head = data.head()

data_labelled_head

tweet_text  \
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...   
1  @jessedee Know about @fludapp ? Awesome iPad/i...   
2  @swonderlin Can not wait for #iPad 2 also. The...   
3  @sxsw I hope this year's festival isn't as cra...   
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...   

  emotion_in_tweet_is_directed_at  \
0                          iPhone   
1              iPad or iPhone App   
2                            iPad   
3              iPad or iPhone App   
4                          Google   

  is_there_an_emotion_directed_at_a_brand_or_product  \
0                                   Negative emotion   
1                                   Positive emotion   
2                                   Positive emotion   
3                                   Negative emotion   
4                                   Positive emotion   

                                  cleaned_tweet_text sentiment_label  
0  wesley83 3g iphone 3 hrs tweeting riseaustin d...        Negative  
1  jessedee know fludapp awesome ipadiphone app y...        Positive  
2              swonderlin wait ipad 2 also sale sxsw        Positive  
3  sxsw hope years festival isnt crashy years iph...        Negative  
4  sxtxstate great stuff fri sxsw marissa mayer g...        Positive

A new column, `sentiment_label`, has been successfully added to the dataset. This column categorizes each tweet's sentiment into one of four possible labels:

- **Positive**: The tweet expresses a positive emotion towards a brand or product.
- **Negative**: The tweet expresses a negative emotion.
- **Neutral**: The tweet does not express any specific emotion towards the brand or product.
- **Unknown**: For tweets where the sentiment is ambiguous or labeled as "I can't tell".

These labels simplify the sentiment categories and offer a more direct interpretation for analysis and modeling.

## Text Vectorization

Text vectorization is the process of converting textual data into numerical format so that it can be fed into machine learning models. Several techniques can be used for text vectorization. Here, we'll cover three of the most common and relevant methods:

- **Count Vectorization (Bag of Words)**

This method represents text as a matrix of token counts. Each row corresponds to a document (in our case, a tweet), and each column corresponds to a unique token in the corpus. The value at a given cell indicates the count of that token in the corresponding document.

- **TF-IDF Vectorization**

This method builds on the count vectorization approach but adjusts the counts based on the importance of a token in a document relative to its frequency across all documents. It helps in giving more weight to terms that are more specific to a particular document.

- **Word Embeddings**

This method represents words in a dense vector space where vectors are chosen such that words with similar meanings are positioned close to each other. For representing a tweet or a document, one common approach is to average the embeddings of all words in it.

For the sake of demonstration, we'll showcase how each of these methods works. However, in a real-world scenario, you'd typically choose one based on the requirements and nature of your problem.

Let's proceed with each of these vectorization techniques:

In [6]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

# Sample of cleaned tweets for demonstration
sample_tweets = data['cleaned_tweet_text'][:1000]

# 1. Count Vectorization (Bag of Words)
count_vectorizer = CountVectorizer(max_features=1000)
count_vectors = count_vectorizer.fit_transform(sample_tweets)
count_vectorized_data = pd.DataFrame(count_vectors.toarray(), columns=count_vectorizer.get_feature_names_out())

# 2. TF-IDF Vectorization
tfidf_vectorizer = TfidfVectorizer(max_features=1000)
tfidf_vectors = tfidf_vectorizer.fit_transform(sample_tweets)
tfidf_vectorized_data = pd.DataFrame(tfidf_vectors.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

# 3. Word Embeddings using Word2Vec
# Tokenizing the cleaned tweets for Word2Vec
tokenized_tweets = [tweet.split() for tweet in sample_tweets]
# Training a Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_tweets, vector_size=100, window=5, min_count=1, workers=4)
# Average the word vectors for each tweet to get a vector representation of the entire tweet
word2vec_vectors = []
for tokens in tokenized_tweets:
    vector_sum = sum([word2vec_model.wv[token] for token in tokens if token in word2vec_model.wv.index_to_key])
    word2vec_vectors.append(vector_sum / len(tokens))
word2vec_vectorized_data = pd.DataFrame(word2vec_vectors)

count_vectorized_data.head(), tfidf_vectorized_data.head(), word2vec_vectorized_data.head()

(   031211  031411  10  100s  11  120035959p  150  16  1pm  1st  ...  zomb  \
 0       0       0   0     0   0           0    0   0    0    0  ...     0   
 1       0       0   0     0   0           0    0   0    0    0  ...     0   
 2       0       0   0     0   0           0    0   0    0    0  ...     0   
 3       0       0   0     0   0           0    0   0    0    0  ...     0   
 4       0       0   0     0   0           0    0   0    0    0  ...     0   
 
    zombie  åè  ûª  ûªll  ûªre  ûªs  ûªt  ûïmention  ûò  
 0       0   0   0     0     0    0    0          0   0  
 1       0   0   0     0     0    0    0          0   0  
 2       0   0   0     0     0    0    0          0   0  
 3       0   0   0     0     0    0    0          0   0  
 4       0   0   0     0     0    0    0          0   0  
 
 [5 rows x 1000 columns],
    031211  031411   10  100s   11  120035959p  150   16  1pm  1st  ...  zomb  \
 0     0.0     0.0  0.0   0.0  0.0         0.0  0.0  0.0  0.0  0.0  ...  

**Count Vectorization (Bag of Words)**
The output showcases the first five tweets transformed into a matrix with 1000 columns. Each column corresponds to a unique word in our corpus (the top 1000 terms in this case), and the entries indicate the frequency of each word in the respective tweets. Most of the values are zeros since only a subset of the 1000 words appear in each tweet.

**TF-IDF Vectorization**
Similar to the Count Vectorization, the structure of the output is a matrix with 1000 columns. However, instead of raw counts, the entries are weighted scores that take into account not just the frequency of a word in a tweet but also its importance in the entire corpus.

**Word Embeddings (Word2Vec)**
The Word2Vec model outputs dense vector representations for words. To represent an entire tweet, we've averaged the vectors of all the words in it. Each tweet is represented by a 100-dimensional vector (as specified by the `vector_size` parameter during model training).

Each of these vectorization techniques has its advantages and is suited for specific types of problems. For sentiment analysis:

- **Count Vectorization and TF-IDF** work well when the corpus isn't too large and when the presence (or absence) of specific words can directly dictate the sentiment. 
- **Word Embeddings**, on the other hand, capture semantic information and work well when context and word relationships are crucial.

With the data now in a numerical format, it's primed for feeding into machine learning models for sentiment analysis.

## Splitting Data into Training and Testing Sets

In [7]:
from sklearn.model_selection import train_test_split

# Using TF-IDF vectors for demonstration
X = tfidf_vectorized_data
y = data['sentiment_label'][:1000]  # Corresponding sentiment labels

# Split the data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 1000), (200, 1000), (800,), (200,))

Based on the provided output:

- The training dataset (\( X_{\text{train}} \)) consists of 800 samples and 1000 features.
- The testing dataset (\( X_{\text{test}} \)) consists of 200 samples and 1000 features.
- The training labels (\( y_{\text{train}} \)) consist of 800 samples.
- The testing labels (\( y_{\text{test}} \)) consist of 200 samples.

This means we have successfully split our dataset into an 80-20 ratio for training and testing, respectively. This common split ratio ensures that we have enough data to train our model while also having a separate set of data to evaluate its performance.

In [8]:
from sklearn.linear_model import LogisticRegression

# Initialize the model
logistic_model = LogisticRegression(max_iter=1000)

# Train the model
logistic_model.fit(X_train, y_train)

# Predict on the test set
logistic_predictions = logistic_model.predict(X_test)

## Machine Learning Models

Sentiment analysis is a classification problem, and several machine learning models are suitable for this task. Here, we'll implement three commonly used models for sentiment analysis:

- **Logistic Regression:** This is a simple yet effective model for binary and multi-class classification problems. It works particularly well when the data is linearly separable.

- **Random Forest Classifier:** This is an ensemble model that can capture complex patterns in the data. It's robust to overfitting, especially when the dataset has many features.

- **Support Vector Machine (SVM):** SVM is effective in high-dimensional spaces and is known for its kernel trick, which can create complex decision boundaries.

For each model:

- We'll train it using the training data.
- Predict sentiments on the test data.
- Evaluate its performance using accuracy and a classification report (which provides precision, recall, and F1-score).

Let's implement and evaluate these models:

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)
logistic_preds = logistic_model.predict(X_test)
logistic_accuracy = accuracy_score(y_test, logistic_preds)
print("Logistic Regression Accuracy:", logistic_accuracy)
print(classification_report(y_test, logistic_preds))

Logistic Regression Accuracy: 0.65
              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        11
     Neutral       0.69      0.86      0.76       121
    Positive       0.53      0.40      0.46        65
     Unknown       0.00      0.00      0.00         3

    accuracy                           0.65       200
   macro avg       0.30      0.31      0.31       200
weighted avg       0.59      0.65      0.61       200



c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100)
rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_preds)
print("Random Forest Accuracy:", rf_accuracy)
print(classification_report(y_test, rf_preds))

Random Forest Accuracy: 0.63
              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        11
     Neutral       0.67      0.84      0.75       121
    Positive       0.51      0.37      0.43        65
     Unknown       0.00      0.00      0.00         3

    accuracy                           0.63       200
   macro avg       0.30      0.30      0.29       200
weighted avg       0.57      0.63      0.59       200



c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
from sklearn.svm import SVC

svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)
svm_preds = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_preds)
print("SVM Accuracy:", svm_accuracy)
print(classification_report(y_test, svm_preds))

SVM Accuracy: 0.61
              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        11
     Neutral       0.67      0.78      0.72       121
    Positive       0.47      0.43      0.45        65
     Unknown       0.00      0.00      0.00         3

    accuracy                           0.61       200
   macro avg       0.29      0.30      0.29       200
weighted avg       0.56      0.61      0.58       200



c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\pkisi\anaconda3\envs\spark-env\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Logistic Regression**:
- **Accuracy**: 65%
- The model performed best for the "Neutral" class with a precision of 69% and a recall of 86%.
- The "Positive" class also has a decent F1-score of 46%.
- However, the model failed to correctly classify the "Negative" and "Unknown" classes.

**Random Forest**:
- **Accuracy**: 59%
- The "Neutral" class again has the best performance with a precision of 64% and a recall of 82%.
- The F1-score for the "Positive" class is 35%.
- Similar to Logistic Regression, Random Forest couldn't classify the "Negative" and "Unknown" classes well.

**Support Vector Machine (SVM)**:
- **Accuracy**: 61%
- The SVM's performance is in between the two previous models.
- The "Neutral" class has a precision of 67% and a recall of 78%.
- The F1-score for the "Positive" class is 45%.
- The "Negative" and "Unknown" classes remain a challenge for the SVM as well.

**Overall Insights**:
- All three models struggle with the "Negative" and "Unknown" classes. This might be due to class imbalance or insufficient distinctive features for these classes.
- The "Neutral" class is the best predicted across all models, which might be because it's the most dominant class in the dataset.
- Logistic Regression has the highest accuracy among the three models, but the difference isn't substantial.

**Recommendations**:
1. **Address Class Imbalance**: The models' inability to predict the "Negative" and "Unknown" classes might be because of their low representation in the dataset. Techniques like oversampling, undersampling, or using the Synthetic Minority Over-sampling Technique (SMOTE) can be explored.
2. **Feature Engineering**: Experiment with different text vectorization techniques or adding more features (e.g., length of tweet, presence of certain keywords) to improve the model's performance.
3. **Hyperparameter Tuning**: Fine-tuning the parameters of the models, especially for Random Forest and SVM, might help in achieving better results.
4. **Deep Learning**: For sentiment analysis, Recurrent Neural Networks (RNNs) and Transformers (like BERT) often outperform traditional machine learning models. If computational resources permit, you can explore these models for better accuracy.

## Deep Learning



In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# LSTM Model
max_words = 10000
max_length = 100
model_lstm = Sequential()
model_lstm.add(Embedding(max_words, 128, input_length=max_length))
model_lstm.add(LSTM(64, dropout=0.2, recurrent_dropout=0.2))
model_lstm.add(Dense(4, activation='softmax'))  # 4 units for 4 sentiment classes
model_lstm.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_lstm.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 128)          1280000   
                                                                 
 lstm (LSTM)                 (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 4)                 260       
                                                                 
Total params: 1,329,668
Trainable params: 1,329,668
Non-trainable params: 0
_________________________________________________________________


In [13]:
from tensorflow.keras.layers import Conv1D, GlobalMaxPooling1D

# 1D CNN Model
model_cnn = Sequential()
model_cnn.add(Embedding(max_words, 128, input_length=max_length))
model_cnn.add(Conv1D(128, 5, activation='relu'))
model_cnn.add(GlobalMaxPooling1D())
model_cnn.add(Dense(4, activation='softmax'))
model_cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_cnn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 100, 128)          1280000   
                                                                 
 conv1d (Conv1D)             (None, 96, 128)           82048     
                                                                 
 global_max_pooling1d (Globa  (None, 128)              0         
 lMaxPooling1D)                                                  
                                                                 
 dense_1 (Dense)             (None, 4)                 516       
                                                                 
Total params: 1,362,564
Trainable params: 1,362,564
Non-trainable params: 0
_________________________________________________________________


In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenization and sequence padding
max_words = 10000
max_length = 100

tokenizer = Tokenizer(num_words=max_words, oov_token='<OOV>')
tokenizer.fit_on_texts(data['cleaned_tweet_text'])
sequences = tokenizer.texts_to_sequences(data['cleaned_tweet_text'])
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post', truncating='post')

# Splitting the data
from sklearn.model_selection import train_test_split
X_padded = padded_sequences
y = pd.get_dummies(data['sentiment_label']).values  # One-hot encoding the labels

X_train_padded, X_test_padded, y_train_padded, y_test_padded = train_test_split(X_padded, y, test_size=0.2, random_state=42)

In [15]:
# Training LSTM
model_lstm.fit(X_train_padded, y_train_padded, epochs=5, batch_size=32, validation_split=0.2)

# Training 1D CNN
model_cnn.fit(X_train_padded, y_train_padded, epochs=5, batch_size=32, validation_split=0.2)

# Evaluation
lstm_score = model_lstm.evaluate(X_test_padded, y_test_padded)
cnn_score = model_cnn.evaluate(X_test_padded, y_test_padded)

print(f"LSTM Test Accuracy: {lstm_score[1]}")
print(f"1D CNN Test Accuracy: {cnn_score[1]}")

Epoch 1/5
182/182 [==============================] - 62s 288ms/step - loss: 0.9458 - accuracy: 0.5822 - val_loss: 0.9341 - val_accuracy: 0.5930
Epoch 2/5
182/182 [==============================] - 50s 275ms/step - loss: 0.9263 - accuracy: 0.5832 - val_loss: 0.9169 - val_accuracy: 0.5930
Epoch 3/5
182/182 [==============================] - 50s 275ms/step - loss: 0.9225 - accuracy: 0.5872 - val_loss: 0.9240 - val_accuracy: 0.5930
Epoch 4/5
182/182 [==============================] - 50s 275ms/step - loss: 0.9256 - accuracy: 0.5872 - val_loss: 0.9161 - val_accuracy: 0.5930
Epoch 5/5
182/182 [==============================] - 50s 276ms/step - loss: 0.9229 - accuracy: 0.5872 - val_loss: 0.9176 - val_accuracy: 0.5930
Epoch 1/5
182/182 [==============================] - 23s 112ms/step - loss: 0.9064 - accuracy: 0.5972 - val_loss: 0.8364 - val_accuracy: 0.6233
Epoch 2/5
182/182 [==============================] - 19s 105ms/step - loss: 0.6514 - accuracy: 0.7419 - val_loss: 0.8194 - val_accuracy:

**LSTM Model**:
- **Training Accuracy**: 58.72%
- **Validation Accuracy**: 59.30%
- **Test Accuracy**: 60.97%

**1D CNN Model**:
- **Training Accuracy**: 93.04%
- **Validation Accuracy**: 64.60%
- **Test Accuracy**: 65.77%

**Analysis**

- The **LSTM model** shows consistent performance throughout training, validation, and testing. However, the accuracy is relatively low, suggesting that the model might not be capturing the complexities in the data. One possible reason for the consistent (but low) accuracy is that the model might be predicting the majority class most of the time.
  
- The **1D CNN model** performs much better. The training accuracy is quite high at 93.04%, suggesting the model has effectively learned patterns in the training data. However, there's a noticeable gap between training and validation/test accuracy, indicating potential overfitting. Despite this, the CNN model's test accuracy is still superior to the LSTM model.

With further fine-tuning and optimization, the 1D CNN model performance can be enhanced even more.

## Hyperparameter Tuning

Hyperparameter tuning is crucial to optimize a model's performance. There are several methods to perform hyperparameter tuning, but the most commonly used methods are:

1. **Grid Search**: This involves exhaustively trying every combination of hyperparameters in a predefined hyperparameter space.
2. **Random Search**: This involves randomly sampling from a distribution of hyperparameters.
3. **Bayesian Optimization**: This uses the concept of probability to predict the set of hyperparameters which might give the best results.

Given the context, we'll look at how to implement hyperparameter tuning for our 1D CNN model using Keras and the Scikit-learn's GridSearchCV.

Here's a general outline:

1. **Wrap Keras Model for use in Scikit-Learn**.
2. **Define Hyperparameter Space**.
3. **Implement Grid Search**.
4. **Evaluate the Best Model**.

Let's discuss each step theoretically:

In [16]:
from keras.wrappers.scikit_learn import KerasClassifier

def create_model(filters=128, kernel_size=5, optimizer='adam'):
    model = Sequential()
    model.add(Embedding(max_words, 128, input_length=max_length))
    model.add(Conv1D(filters, kernel_size, activation='relu'))
    model.add(GlobalMaxPooling1D())
    model.add(Dense(4, activation='softmax'))
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

model = KerasClassifier(build_fn=create_model, epochs=5, batch_size=32)

C:\Users\pkisi\AppData\Local\Temp\ipykernel_10696\4093822848.py:12: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  model = KerasClassifier(build_fn=create_model, epochs=5, batch_size=32)


In [17]:
param_grid = {
    'filters': [64, 128, 256],
    'kernel_size': [3, 5, 7],
    'optimizer': ['adam', 'rmsprop'],
    'epochs': [3, 5],
    'batch_size': [16, 32, 64]
}

In [18]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3)
grid_result = grid.fit(X_train_padded, y_train_padded)

Epoch 1/3


303/303 [==============================] - 14s 41ms/step - loss: 0.9165 - accuracy: 0.5923
Epoch 2/3
303/303 [==============================] - 13s 44ms/step - loss: 0.6851 - accuracy: 0.7372
Epoch 3/3
152/152 [==============================] - 2s 10ms/step - loss: 0.8805 - accuracy: 0.6589
Epoch 1/3
303/303 [==============================] - 15s 43ms/step - loss: 0.8960 - accuracy: 0.6109
Epoch 2/3
303/303 [==============================] - 14s 45ms/step - loss: 0.6445 - accuracy: 0.7521
Epoch 3/3
152/152 [==============================] - 2s 10ms/step - loss: 0.9506 - accuracy: 0.6494
Epoch 1/3
303/303 [==============================] - 16s 46ms/step - loss: 0.9103 - accuracy: 0.5986
Epoch 2/3
303/303 [==============================] - 14s 45ms/step - loss: 0.6636 - accuracy: 0.7445
Epoch 3/3
152/152 [==============================] - 2s 9ms/step - loss: 0.8757 - accuracy: 0.6629
Epoch 1/3
303/303 [==============================] - 11s 32ms/step - loss: 0.9047 - accuracy: 0.6008
Epoc

In [19]:
print("Best Score: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best Score: 0.662348 using {'batch_size': 16, 'epochs': 3, 'filters': 128, 'kernel_size': 7, 'optimizer': 'rmsprop'}
0.657112 (0.005664) with: {'batch_size': 16, 'epochs': 3, 'filters': 64, 'kernel_size': 3, 'optimizer': 'adam'}
0.653668 (0.015856) with: {'batch_size': 16, 'epochs': 3, 'filters': 64, 'kernel_size': 3, 'optimizer': 'rmsprop'}
0.653667 (0.011200) with: {'batch_size': 16, 'epochs': 3, 'filters': 64, 'kernel_size': 5, 'optimizer': 'adam'}
0.657662 (0.008242) with: {'batch_size': 16, 'epochs': 3, 'filters': 64, 'kernel_size': 5, 'optimizer': 'rmsprop'}
0.643331 (0.006656) with: {'batch_size': 16, 'epochs': 3, 'filters': 64, 'kernel_size': 7, 'optimizer': 'adam'}
0.661109 (0.012296) with: {'batch_size': 16, 'epochs': 3, 'filters': 64, 'kernel_size': 7, 'optimizer': 'rmsprop'}
0.653115 (0.004365) with: {'batch_size': 16, 'epochs': 3, 'filters': 128, 'kernel_size': 3, 'optimizer': 'adam'}
0.657802 (0.009712) with: {'batch_size': 16, 'epochs': 3, 'filters': 128, 'kernel_size': 

## Conclusion

1. **Significance of Sentiment Analysis**: At Nyika Analytika, we recognize the transformative power of sentiment analysis, particularly in today's digital age. Platforms such as Twitter serve as reservoirs of public sentiment, capturing the zeitgeist of the digital populace in real-time. Tapping into these vast repositories can furnish us with a deep understanding of public reactions, a knowledge invaluable to esteemed bodies like the Kenyan Parliamentary ICT Committee. Our dedicated utilization of state-of-the-art Natural Language Processing (NLP) techniques ensures that our methodologies are at the forefront of data science.

2. **Dataset Inference**: The dataset we've meticulously sourced encompasses tweets targeting two of the world's technological behemoths: Apple and Google. Our initial exploration divulged variations in sentiment distributions and highlighted particular brand/product mentions. Furthermore, the presence of missing values in the dataset has accentuated the necessity for a rigorous and thorough data cleansing process.

3. **Performance Metrics of Our Models**:
   - **Logistic Regression**: Our meticulously trained model achieved an accuracy rate of 65%. It showcased commendable prowess in categorizing Neutral sentiments, reflecting an F1-score of 0.76. This indicates a harmonious balance between precision and recall for this specific category. Nevertheless, we acknowledge room for improvement in the categories of Negative and Unknown sentiments.
   - **Random Forest**: This model, another jewel in our analytical arsenal, registered an accuracy of 63%. Echoing the Logistic Regression model, it exhibited a pronounced affinity for the Neutral sentiments with an F1-score of 0.75. We are actively seeking to enhance its efficacy for other sentiment categories.

## Recommendations

1. **Data Cleansing and Refinement**: 
   - We advocate for the judicious handling of missing values. Their importance will dictate whether imputation or row deletion is the optimal strategy.
   - We further recommend the incorporation of advanced text pre-processing techniques, encompassing stemming, lemmatization, and the elimination of special characters, to elevate the caliber of data being processed.

2. **Innovative Feature Engineering**:
   - We suggest delving into avant-garde text vectorization methodologies like TF-IDF, Word2Vec, or Doc2Vec. Their ability to encapsulate semantic word relationships can be the linchpin to enhancing model performance.
   - Consider the extraction of nuanced features from tweets, such as tweet length, URL presence, or specific hashtag usage, as they might wield untapped predictive prowess.

3. **Exploring Model Horizons**:
   - We propose experimentation with intricate architectures like Neural Networks and ensemble methods. Models imbued with Deep Learning capabilities, such as LSTM or GRU, are renowned for their efficacy in sentiment analysis tasks, given their prowess in discerning textual sequences.
   - We also recommend a rigorous phase of hyperparameter fine-tuning for our current models, ensuring they operate at their zenith.

4. **Addressing Class Imbalance**:
   - Our introspection has revealed potential class imbalances. To rectify this, we suggest techniques like oversampling, undersampling, or even the adoption of synthetic data methodologies like SMOTE.

5. **Augmenting Data Sources**:
   - In our quest for a holistic sentiment understanding, we're considering the integration of data from diverse social media platforms and tech forums. This multidimensional approach promises a more comprehensive sentiment landscape.

6. **Iterative Feedback Mechanism**:
   - We're in the process of instituting a feedback loop where our model's predictions undergo validation against real-world outcomes. This iterative process promises continuous model refinement.

7. **Engaging with Stakeholders**:
   - We underscore the importance of continuous dialogue with the Kenyan Parliamentary ICT Committee. This ensures our analytical endeavors remain aligned with their evolving requirements, guaranteeing actionable and pertinent insights.

At Nyika Analytika, we believe in the transformative potential of sentiment analysis. Our relentless quest for perfection, combined with the above recommendations, aims to empower Kenya's Parliamentary ICT Committee, aiding them in sculpting a future aligned with public sentiment.